/*
    FMOD Studio Common Header Placeholder

    Replace with actual FMOD SDK headers.
*/

#pragma once

#ifndef FMOD_STUDIO_COMMON_H
#define FMOD_STUDIO_COMMON_H

typedef unsigned int FMOD_STUDIO_INITFLAGS;
typedef unsigned int FMOD_STUDIO_LOAD_BANK_FLAGS;
typedef unsigned int FMOD_STUDIO_LOAD_MEMORY_MODE;
typedef unsigned int FMOD_STUDIO_STOP_MODE;

typedef enum {
    FMOD_STUDIO_PLAYBACK_PLAYING,
    FMOD_STUDIO_PLAYBACK_SUSTAINING,
    FMOD_STUDIO_PLAYBACK_STOPPED,
    FMOD_STUDIO_PLAYBACK_STARTING,
    FMOD_STUDIO_PLAYBACK_STOPPING
} FMOD_STUDIO_PLAYBACK_STATE;

#define FMOD_STUDIO_INIT_NORMAL 0x00000000
#define FMOD_STUDIO_LOAD_BANK_NORMAL 0x00000000
#define FMOD_STUDIO_LOAD_MEMORY 0x00000001
#define FMOD_STUDIO_STOP_IMMEDIATE 0
#define FMOD_STUDIO_STOP_ALLOWFADEOUT 1

#endif // FMOD_STUDIO_COMMON_H
